### ISSUE TITLE
Question: How to upload to root directory on S3

### ISSUE THREAD

**Issue by morugu** [jamestalmage/s3-static-site-uploader#20]
my app dictionary
```
app - dist - html.index (and other build files.
```

my upload conf
```
module.exports = {
    credentials:"aws-credentials.json",
    bucketName:"bucketName",
    patterns:[
        "dist/*.html"
    ]
}
```

S3 directory
```
root - dist - index.html
```

The truth is that I want the following directory on S3
```
root - index.html
```

please tell me how to editing conf to last directory pattern,
thanks.

**Comment by SergioGeeK7** [comment]
same issue here, my config files are being uploaded and I don't want that

**Comment by kyledetella** [comment]
I ran into a similar issue and here is how I solved it:

In my deploy script (which kicks off my build task), I copy `aws-upload.conf.js` and `aws-credentials.json` to `dist` and then run the upload task from the `dist` directory. The `aws-*` files are ignored and _not_ uploaded to S3. 

When my `build` script is run, it runs transforms on the JS/CSS in `public/` and writes them to `dist` along with `index.html`. So after running the build, my project structure looks something like this:

```
.
├── aws-credentials.json
├── aws-upload.conf.js
├── dist
│   ├── aws-credentials.json
│   ├── aws-upload.conf.js
│   ├── index.html
│   └── public
│       ├── app.css
│       └── app.js
├── index.html
├── package.json
└── public
    ├── app.css
    └── app.js
```

My `aws-upload.conf.js` looks like this:

```js
module.exports = {
  credentials: 'aws-credentials.json',
  bucketName: '<bucket-name>',
  patterns:[
    'public/**/*',
    'index.html',
  ]
}
```

My deploy task looks something like this (I am using a bash script to execute the deploy, but it should work from an npm/yarn script too):

**tasks/deploy**

```bash
#!/usr/bin/env bash
set -e

echo ""
echo -e "| Preparing build..."
yarn build

echo ""
echo -e "| Initiating deploy"
cp aws-* ./dist
cd dist
../node_modules/.bin/s3-upload

echo ""
echo -e "| Deploy complete"
cd ../
rm -rf dist
```

It is important to make sure the `aws-upload.conf.js` and `aws-credentials.json` are in the same directory (which represent the root for the deploy) to make this work. I hope this helps.

**Comment by nick-michael** [comment]
For anyone else who runs into this issue - I've managed to find a nice little workaround.

Assuming you have your `aws-credentials.json` and `aws-upload.conf.js` in the root directory, and you want to upload the contents of a `dist` folder without uploding the folder itself:

In your npm scripts, you can do: `"deploy": "(cd ./dist && s3-upload ./../aws-upload.conf.js)"`

Then, in your `aws-upload.conf.js`, change the credentials path to `"../aws-credentials.json"` and all your patterns should be adjusted as if they are paths from inside the dist folder.

**Comment by username3110** [comment]
i have to upload ads.txt file on the root directory on aws, but don't know where is root directory. please help me fix it
